// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRHlydRX8Gj-Go4Pcs2LS3scAosp2Nqq8',
    appId: '1:1009274616783:web:f4e7214f4437f22c1470ba',
    messagingSenderId: '1009274616783',
    projectId: 'asdsa-d5100',
    authDomain: 'asdsa-d5100.firebaseapp.com',
    storageBucket: 'asdsa-d5100.firebasestorage.app',
    measurementId: 'G-2GQH7Y4MF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLk40n_XfbCCeVMayGDjAHxNp3GQOn5NY',
    appId: '1:1009274616783:android:6cab20aa275f0e061470ba',
    messagingSenderId: '1009274616783',
    projectId: 'asdsa-d5100',
    storageBucket: 'asdsa-d5100.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDptKYZ9Q4zPiT8e4i-mphYeWrprBCjkKM',
    appId: '1:1009274616783:ios:8c2d868a4c65c2c01470ba',
    messagingSenderId: '1009274616783',
    projectId: 'asdsa-d5100',
    storageBucket: 'asdsa-d5100.firebasestorage.app',
    iosBundleId: 'com.example.tabletime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDptKYZ9Q4zPiT8e4i-mphYeWrprBCjkKM',
    appId: '1:1009274616783:ios:8c2d868a4c65c2c01470ba',
    messagingSenderId: '1009274616783',
    projectId: 'asdsa-d5100',
    storageBucket: 'asdsa-d5100.firebasestorage.app',
    iosBundleId: 'com.example.tabletime',
  );
}
